### ISSUE TITLE
运行yarn dist:win32打包出来的exe执行报错

### ISSUE THREAD

**Issue by denglouhen** [AgoraIO-Extensions/electron-agora-rtc-ng#18]
![image](https://user-images.githubusercontent.com/26452618/186570107-5faa5536-7295-4bc8-8591-f51e52d21097.png)

我的系统是window10 64 bit

**Comment by denglouhen** [comment]
我配置了agora_electron_sdk_arch=x64，然后
"agora_electron": {
    "prebuilt": true,
    "arch": "x64"
  }
打出来的dist:win64是正常的，dist:win32的包报错。我要怎么做才能打出正常的win32的包？

**Comment by syanbo** [comment]
build配置的  "asar": false 试一下

**Comment by denglouhen** [comment]
> build配置的 "asar": false 试一下

在声网论坛得到了回复，说是windows无法同时打win32和win64的包，需要单独npm install不同版本sdk后打包。没什么问题了。
