### ISSUE TITLE
getPlaybackDeviceInfo、getRecordingDeviceInfo无法记忆

### ISSUE THREAD

**Issue by syanbo** [AgoraIO-Extensions/electron-agora-rtc-ng#21]
setRecordingDevice、setPlaybackDevice修改设备后，重新进入房间getPlaybackDeviceInfo、getRecordingDeviceInfo变了

**Comment by LichKing-2234** [comment]
This repo has been migrated to https://github.com/AgoraIO-Extensions/Electron-SDK
