### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by v2018z** [AgoraIO-Extensions/electron-agora-rtc-ng#22]
使用环境：

一台全新的 windows 10
x64位

使用步骤：

1、clone 此项目
2、cd example 
3、yarn 
4、yarn dev

页面会显示
```
Error: The specified module could not be found. ......  agora_node_ext.node
```

根据资料显示，应该是缺少某些重要的 dll 文件。
测试下来，安装 visual studio C++ 相关模块后能正常运行。

**Comment by LichKing-2234** [comment]
麻烦清理node_modules、.lock等文件夹后，install rc.3 再试试

**Comment by v2018z** [comment]
> 麻烦清理node_modules、.lock等文件夹后，install rc.3 再试试

重新clone example ，清理 node_modules，使用  "agora-electron-sdk": "4.0.0-rc.3",  没有编译出 build 目录。。  改为 4.0.0-test.3 或 其他版本均能编译  build 目录，但依然 会报 此 issue 的错

**Comment by v2018z** [comment]
> 麻烦清理node_modules、.lock等文件夹后，install rc.3 再试试

补充，build 文件夹有了，然而依然报同样的错~

**Comment by zhangtao1104** [comment]
https://github.com/lucasg/Dependencies/releases
能帮忙用这个程序在那太机器上 run 下，然后把 agora_node_ext.node 库拖到 Dependencies 程序里，看下具体是哪个依赖库缺失吗？ 如果能这样做，帮忙提供个截图给我们。

**Comment by zhangtao1104** [comment]
或者能安装个向日葵吗？把账号验证码发给我，我远程链接上去直接操作下也可以。

**Comment by v2018z** [comment]
![VnM7F6LEav](https://user-images.githubusercontent.com/3415207/190322531-697a319f-eff2-472a-b823-855a14a1d554.jpg)

**Comment by zhangtao1104** [comment]
感谢，知道原因了，会在下个版本更新修复这个依赖库问题。

**Comment by v2018z** [comment]
> https://github.com/lucasg/Dependencies/releases 能帮忙用这个程序在那太机器上 run 下，然后把 agora_node_ext.node 库拖到 Dependencies 程序里，看下具体是哪个依赖库缺失吗？ 如果能这样做，帮忙提供个截图给我们。

hello ， 截图已发。应该是缺少图中那三个 dll

**Comment by v2018z** [comment]
> 



> 感谢，知道原因了，会在下个版本更新修复这个依赖库问题。

好的，辛苦～ 坐等

**Comment by LichKing-2234** [comment]
This repo has been migrated to https://github.com/AgoraIO-Extensions/Electron-SDK
